version: '3.4'

services:
  adguard:
    image: adguard/adguardhome
    hostname: "{{.Node.Hostname}}-{{.Service.Name}}"
    domainname: ${DOMAIN_NAME}
    deploy:
      mode: global
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 80
        published: ${ADGUARD_WEBPORT:-80}
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: udp
        mode: host
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    environment:
      - TZ=${TZ:-UTC}
    volumes:
      - /etc/adguardhome/work:/opt/adguardhome/work:rw
      - /etc/adguardhome/conf:/opt/adguardhome/conf:rw
      - /etc/adguardhome/resolv.conf:/etc/resolv.conf
    restart: unless-stopped
  pihole-unbound:
    image: kgshank/pihole-unbound
    hostname: "{{.Node.Hostname}}-{{.Service.Name}}"
    domainname: ${DOMAIN_NAME}
    deploy:
      mode: global
    ports:
      - target: 53
        published: 54
        protocol: tcp
        mode: host
      - target: 53
        published: 54
        protocol: udp
        mode: host
      - target: 80
        published: ${PIHOLE_WEBPORT:-80}
        protocol: tcp
        mode: host
    environment:
      #- FTLCONF_LOCAL_IPV4='{{ .Status.Addr  }}'
      - TZ=${TZ:-UTC}
      - REV_SERVER=${REV_SERVER:-false}
      - REV_SERVER_TARGET=${REV_SERVER_TARGET}
      - REV_SERVER_DOMAIN=${REV_SERVER_DOMAIN}
      - REV_SERVER_CIDR=${REV_SERVER_CIDR}
      - PIHOLE_DNS_=127.0.0.1#5335
      - DNSSEC="true"
      - DNSMASQ_LISTENING=all
      - HOSTNAME={{.Node.Hostname}}-pihole
      - DOMAIN_NAME=${DOMAIN_NAME}
      - WEBPASSWORD_FILE=${WEBPASSWORD_FILE}
    secrets:
      - pihole_pass
    volumes:
      - /etc/pihole/config:/etc/pihole:rw
      - /etc/pihole/dnsmasq.d:/etc/dnsmasq.d:rw
      - /etc/pihole/resolv.conf:/etc/resolv.conf
    restart: unless-stopped
secrets:
  pihole_pass:
    external: true
