version: '3.4'

services:
  adguard-unbound:
    image: kgshank/adguard-unbound
    hostname: "{{.Node.Hostname}}-{{.Service.Name}}"
    domainname: ${DOMAIN_NAME}
    deploy:
      mode: global
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: ${ADGUARD_WEBPORT:-80}
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: udp
        mode: host
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    environment:
      #- FTLCONF_LOCAL_IPV4='{{ .Status.Addr  }}'
      - TZ=${TZ:-UTC}
    volumes:
      - /etc/adguardhome/work:/opt/adguardhome/work:rw
      - /etc/adguardhome/conf:/opt/adguardhome/conf:rw
      - /etc/adguardhome/resolv.conf:/etc/resolv.conf
    restart: unless-stopped

